version: "3.8"
services:
  music-bot:
    image: tjvg4m34r13/microtech_radiobot:latest
    container_name: music-bot
    restart: always
    volumes:
      - bot-data:/app/data
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - DB_PATH=/app/data/database.sqlite
    env_file:
      - .env

volumes:
  bot-data:
