version: "3.8"
services:
  music-bot:
    image: tjvg4m34r13/microtech_radiobot:latest
    container_name: music-bot
    restart: always
    volumes:
      - bot-data:/app/data
    environment:
      - DB_PATH=/app/data/database.sqlite
    env_file:
      - stack.env

volumes:
  bot-data:
